# Generated by Django 4.2.1 on 2023-05-20 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='authors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='article.authors'),
        ),
    ]
